services:
  - type: web
    name: mem9
    env: go
    buildCommand: "cd server && go build -o app ./cmd/mnemo-server"
    startCommand: "./server/app"
    envVars:
      - key: MNEMO_DSN
        value: 4FKFSjsHE2BfSd5.root:VTyj3LXV3iNWZ3T1@tcp(gateway01.us-east-1.prod.aws.tidbcloud.com:4000)/mnemos?parseTime=true
      - key: MNEMO_PORT
        value: "8080"
